=== sodascience/metasyn/metasyn/schema/generative_metadata_format.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "http://sodascience.github.io/generative_metadata_format/core/1.0.0/generative_metadata_format",
    "type": "object",
    "properties": {
        "n_rows": {"type": "number"},
        "n_columns": {"type": "number"},
        "provenance": {
            "type": "object",
            "properties": {
                "created by": {"type": "object"},
                "creation time": {"type": "string"}
            },
            "required": ["created by", "creation time"]
        },
        "vars": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "description": {"type": "string"},
                    "type": {"enum": ["discrete", "continuous", "string", "categorical", "date", "datetime", "time"]},
                    "dtype": {"type": "string"},
                    "prop_missing": {"type": "number"},
                    "distribution": {
                        "$ref": "#/$defs/all_dist_def"
                    }
                }
            },
            "required": ["name", "type", "dtype", "provenance", "prop_missing", "distribution"]
        }
    },
    "required": ["n_rows", "n_columns", "vars"],

    "$defs": {
        "MultinoulliDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "MultinoulliDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "labels": {"type": "array", "items": {"type": "string"}, "uniqueItems": true},
                        "probs": {"type": "array", "items": {"type": "number"}}
                    },
                    "required": ["labels", "probs"]
                }
            }
        },
        "RegexDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "RegexDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "re_list": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "prefixItems": [{"type": "string"}, {"type": "number"}],
                                "minItems": 2,
                                "additionalItems": false
                            }
                        }
                    },
                    "required": ["re_list"]
                }
            }
        },
        "UniqueRegexDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "UniqueRegexDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "re_list": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "prefixItems": [{"type": "string"}, {"type": "number"}],
                                "minItems": 2,
                                "additionalItems": false
                            }
                        }
                    },
                    "required": ["re_list"]
                }
            }
        },
        "FakerDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "FakerDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "faker_type": {"type": "string"},
                        "locale": {"type": "string"}
                    },
                    "required": ["faker_type", "locale"]
                }
            }
        },
        "UniqueKeyDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "UniqueKeyDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "low": {"type": "integer"},
                        "consecutive": {"enum": [0, 1]}
                    },
                    "required": ["low", "consecutive"]
                }
            }
        },
        "DiscreteUniformDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "DiscreteUniformDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "low": {"type": "integer"},
                        "high": {"type": "integer"}
                    },
                    "required": ["low", "high"]
                }
            }
        },
        "PoissonDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "PoissonDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "mu": {"type": "number"}
                    },
                    "required": ["mu"]
                }
            }
        },
        "UniformDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "UniformDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "min_val": {"type": "number"},
                        "max_val": {"type": "number"}
                    },
                    "required": ["min_val", "max_val"]
                }
            }
        },
        "NormalDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "NormalDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "mean": {"type": "number"},
                        "std_dev": {"type": "number"}
                    },
                    "required": ["mean", "std_dev"]
                }
            }
        },
        "LogNormalDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "LogNormalDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "mu": {"type": "number"},
                        "sigma": {"type": "number"}
                    },
                    "required": ["mu", "sigma"]
                }
            }
        },
        "TruncatedNormalDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "TruncatedNormalDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "lower_bound": {"type": "number"},
                        "upper_bound": {"type": "number"},
                        "mu": {"type": "number"},
                        "sigma": {"type": "number"}
                    },
                    "required": ["lower_bound", "upper_bound", "mu", "sigma"]
                }
            }
        },
        "ExponentialDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "ExponentialDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "rate": {"type": "number"}
                    },
                    "required": ["rate"]
                }
            }
        },
        "UniformDateTimeDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "UniformDateTimeDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "start": {"type": "string"},
                        "end": {"type": "string"},
                        "precision": {"type": "string"}
                    },
                    "required": ["start", "end", "precision"]
                }
            }
        },
        "UniformDateDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "UniformDateDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "start": {"type": "string"},
                        "end": {"type": "string"}
                    },
                    "required": ["start", "end"]
                }
            }
        },
        "UniformTimeDistribution": {
            "type": "object",
            "properties": {
                "name": {"const": "UniformTimeDistribution"},
                "parameters": {
                    "type": "object",
                    "properties": {
                        "start": {"type": "string"},
                        "end": {"type": "string"},
                        "precision": {"type": "string"}
                    },
                    "required": ["start", "end", "precision"]
                }
            }
        },
        "all_dist_def": {
            "anyOf": [
                {"$ref": "#/$defs/MultinoulliDistribution"},
                {"$ref": "#/$defs/RegexDistribution"},
                {"$ref": "#/$defs/UniqueRegexDistribution"},
                {"$ref": "#/$defs/FakerDistribution"},
                {"$ref": "#/$defs/LogNormalDistribution"},
                {"$ref": "#/$defs/NormalDistribution"},
                {"$ref": "#/$defs/UniformDistribution"},
                {"$ref": "#/$defs/DiscreteUniformDistribution"},
                {"$ref": "#/$defs/PoissonDistribution"},
                {"$ref": "#/$defs/UniqueKeyDistribution"},
                {"$ref": "#/$defs/UniformDateDistribution"},
                {"$ref": "#/$defs/UniformTimeDistribution"},
                {"$ref": "#/$defs/UniformDateTimeDistribution"},
                {"$ref": "#/$defs/TruncatedNormalDistribution"},
                {"$ref": "#/$defs/ExponentialDistribution"}
            ]
        }
    }
}

=== sodascience/metasyn/examples/basic_example.json
{
    "n_rows": 5,
    "n_columns": 5,
    "provenance": {
        "created by": {
            "name": "metasyn",
            "version": "0.4.0"
        },
        "creation time": "2023-08-07T12:04:40.669740"
    },
    "vars": [
        {
            "name": "ID",
            "type": "discrete",
            "dtype": "Int64",
            "prop_missing": 0.0,
            "distribution": {
                "implements": "core.unique_key",
                "provenance": "builtin",
                "class_name": "UniqueKeyDistribution",
                "parameters": {
                    "low": 1,
                    "consecutive": 1
                }
            }
        },
        {
            "name": "fruits",
            "type": "categorical",
            "dtype": "Categorical",
            "prop_missing": 0.0,
            "distribution": {
                "implements": "core.multinoulli",
                "provenance": "builtin",
                "class_name": "MultinoulliDistribution",
                "parameters": {
                    "labels": [
                        "apple",
                        "banana"
                    ],
                    "probs": [
                        0.4,
                        0.6
                    ]
                }
            }
        },
        {
            "name": "B",
            "type": "discrete",
            "dtype": "Int64",
            "prop_missing": 0.0,
            "distribution": {
                "implements": "core.poisson",
                "provenance": "builtin",
                "class_name": "PoissonDistribution",
                "parameters": {
                    "mu": 3.0
                }
            }
        },
        {
            "name": "cars",
            "type": "categorical",
            "dtype": "Categorical",
            "prop_missing": 0.0,
            "distribution": {
                "implements": "core.multinoulli",
                "provenance": "builtin",
                "class_name": "MultinoulliDistribution",
                "parameters": {
                    "labels": [
                        "audi",
                        "beetle"
                    ],
                    "probs": [
                        0.2,
                        0.8
                    ]
                }
            }
        },
        {
            "name": "optional",
            "type": "discrete",
            "dtype": "Int64",
            "prop_missing": 0.2,
            "distribution": {
                "implements": "core.discrete_uniform",
                "provenance": "builtin",
                "class_name": "DiscreteUniformDistribution",
                "parameters": {
                    "low": -30,
                    "high": 301
                }
            }
        }
    ]
}
